name: Zip on Push to Main

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Zip files
      run: zip -r release.zip .

    - name: Upload to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: release.zip
        path: release.zip
